### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-core-react-redux-containers#1]
- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- fix README, package*, NOTICE/LICENSE
- publish under `@marklogic-community`

**Comment by grtjn** [comment]
I have done everything except publish to npm, because test suite doesn't run clean, and I wasn't entirely sure how to build the dist..

**Comment by grtjn** [comment]
Note: don't forget to update your remotes, and do a `git fetch -p`

**Comment by patrickmcelwee** [comment]
I will create a deprecated README in order to finish this.
